name: Daily parsing

on:
  schedule:
    - cron: "0 */18 * * *" # Run every 18 hours
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest
    
    permissions: write-all
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Decrypt large secret
        run: ./src/utils/decrypt_secret.sh
        shell: bash
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Test
        run: ls ./
        
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Run script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: Rscript src/scripts/daily_parsing.R
        
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          
          # Add all CSV files in data/daily/ directory
          git add ./data/daily/*.csv        
          git commit -m "Daily parsing commit on $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions