name: Daily parsing

on:
  schedule:
    - cron: "0 */18 * * *" # Run every 18 hours
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        shell: bash
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Install R dependencies
        run: |
          Rscript -e "install.packages(c('spotifyr', 'dplyr', 'lubridate'), repos='https://cran.rstudio.com/')"
        
      - name: Run daily parsing script
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: Rscript daily_parsing.R
        
      - name: Commit and push changes
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./daily_listen/history.txt
          git add ./daily_listen/*.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily parsing update - $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi