name: Quarto Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.qmd'
      - '_quarto.yml'
      - 'styles.css'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # If your documents need R packages, uncomment and list them or use a lockfile
      # - name: Install R package dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     extra-packages: |
      #       any::knitr
      #       any::rmarkdown

      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .

      - name: Publish to GitHub Pages (gh-pages)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

